version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=DOES-NOT-MATTER
      - POSTGRES_USER=$USER
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./pgconf/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./pgconf/server.crt:/var/lib/postgresql/server.crt:ro
      - ./pgconf/server.key:/var/lib/postgresql/server.key:ro
      - ./pgconf/ca.crt:/var/lib/postgresql/ca.crt:ro
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/ca.crt
    ports:
      - "5432:5432"
